### ISSUE TITLE
Sorry I cannot reply to your tag

### ISSUE THREAD

**Issue by eddiejaoude** [CodingSpecies/codingspecies#2]
Hi @CodingSpecies 

I am not ignoring you in your tag, I got blocked from the Organisation - probably because I report the founder and the organisation for spamming people on GitHub

This is what I see. What happened to the founder of the organisation?

<img width="1326" alt="Screenshot 2021-09-15 at 20 09 37" src="https://user-images.githubusercontent.com/624760/133495340-79d0bce9-a903-48e3-9d61-3b12d51d161f.png">

**Comment by NS007-dev** [comment]
@eddiejaoude as this is public please see as private repo [this](https://github.com/CodingSpecies/repo-discuss-org/invitations)

**Comment by eddiejaoude** [comment]
It is best to discuss in public, I am focused on Open Source and the community 🤓

**Comment by NS007-dev** [comment]
@eddiejaoude I am not sure what has happened, as I was also removed as admin to the organisation. Thank you.

**Comment by eddiejaoude** [comment]
ok 🤓
