### ISSUE TITLE
[BUG] Broken image link (Logo)

### ISSUE THREAD

**Issue by Pradumnasaraf** [CodingSpecies/codingspecies#3]
#### Boken logo in the README, look like the image is no more available at that destination, that's why it can able to fetch it.
![Screenshot from 2022-06-02 07-23-36](https://user-images.githubusercontent.com/51878265/171530527-677a6ba0-b813-407f-ad06-40c221cc1def.png)

**Comment by NS007-dev** [comment]
@Pradumnasaraf thank you for pointing this out, I really appreciate it!
I am planning to completely redesign my readme, so I will change the broken image.
I will leave this issue open until I change the image. 
Thank you!

**Comment by Pradumnasaraf** [comment]
> @Pradumnasaraf thank you for pointing this out, I really appreciate it!
> I am planning to completely redesign my readme, so I will change the broken image.
> I will leave this issue open until I change the image. 
> Thank you!


Welcome, Oh that's nice, good luck :)

**Comment by NS007-dev** [comment]
@Pradumnasaraf I have replaced the broken image. Thank you.
